package com.agroknow;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 *
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Fri Mar 08 16:20:03 EET 2019 by mihalis
 */

public class Vocabulary {

    private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#allowedUnitOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property ALLOWED_UNIT_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ALLOWED_UNIT_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#allowedUnitOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#baseDimensionEnumeration
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property BASE_DIMENSION_ENUMERATION.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BASE_DIMENSION_ENUMERATION = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#baseDimensionEnumeration"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#baseQuantityKindOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property BASE_QUANTITY_KIND_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BASE_QUANTITY_KIND_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#baseQuantityKindOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#baseUnitOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property BASE_UNIT_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BASE_UNIT_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#baseUnitOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#basisElement
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property BASIS_ELEMENT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BASIS_ELEMENT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#basisElement"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#coherentDerivedUnitOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DERIVED_UNIT_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COHERENT_DERIVED_UNIT_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#coherentDerivedUnitOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#coherentUnitOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property COHERENT_UNIT_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COHERENT_UNIT_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#coherentUnitOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#coherentUnitSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property COHERENT_UNIT_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COHERENT_UNIT_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#coherentUnitSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#default
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEFAULT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEFAULT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#default"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#definedUnitOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEFINED_UNIT_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEFINED_UNIT_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#definedUnitOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#derivedQuantityKindOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DERIVED_QUANTITY_KIND_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DERIVED_QUANTITY_KIND_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#derivedQuantityKindOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#derivedUnitOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DERIVED_UNIT_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DERIVED_UNIT_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#derivedUnitOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#dimensionInverse
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DIMENSION_INVERSE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DIMENSION_INVERSE = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#dimensionInverse"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#element
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property ELEMENT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ELEMENT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#element"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#elementKind
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property ELEMENT_KIND.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ELEMENT_KIND = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#elementKind"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#exactMatch
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXACT_MATCH.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXACT_MATCH = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#exactMatch"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#generalization
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property GENERALIZATION.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_GENERALIZATION = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#generalization"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#prefixUnitOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property PREFIX_UNIT_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PREFIX_UNIT_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#prefixUnitOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#quantity
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property QUANTITY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_QUANTITY = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#quantity"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#quantityKind
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property QUANTITY_KIND.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_QUANTITY_KIND = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#quantityKind"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#quantityKindOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property QUANTITY_KIND_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_QUANTITY_KIND_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#quantityKindOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#quantityValue
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property QUANTITY_VALUE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_QUANTITY_VALUE = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#quantityValue"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#referenceThing
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERENCE_THING.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERENCE_THING = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#referenceThing"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#referenceUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERENCE_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERENCE_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#referenceUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#specialization
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property SPECIALIZATION.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SPECIALIZATION = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#specialization"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemAllowedUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property ALLOWED_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ALLOWED_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemAllowedUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemBaseQuantityKind
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property SYSTEM_BASE_QUANTITY_KIND.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SYSTEM_BASE_QUANTITY_KIND = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemBaseQuantityKind"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemBaseUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property BASE_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BASE_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemBaseUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemCoherentDerivedUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property COHERENT_DERIVED_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COHERENT_DERIVED_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemCoherentDerivedUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemCoherentUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property COHERENT_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COHERENT_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemCoherentUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemDefinedUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEFINED_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEFINED_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemDefinedUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemDerivedQuantityKind
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property SYSTEM_DERIVED_QUANTITY_KIND.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SYSTEM_DERIVED_QUANTITY_KIND = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemDerivedQuantityKind"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemDerivedUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DERIVED_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DERIVED_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemDerivedUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemDimension
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property SYSTEM_DIMENSION.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SYSTEM_DIMENSION = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemDimension"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemPrefixUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property PREFIX_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PREFIX_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemPrefixUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemQuantityKind
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property SYSTEM_QUANTITY_KIND.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SYSTEM_QUANTITY_KIND = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemQuantityKind"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#systemUnit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property SYSTEM_UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SYSTEM_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#systemUnit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#unit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property UNIT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_UNIT = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#unit"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#unitFor
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property UNIT_FOR.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_UNIT_FOR = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#unitFor"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#unitOfSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property UNIT_OF_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_UNIT_OF_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#unitOfSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#unitSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property UNIT_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_UNIT_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#unitSystem"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#value
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property VALUE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_VALUE = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#value"));

    /* ***************************************************
     * Object Property http://qudt.org/schema/qudt#valueQuantity
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property VALUE_FOR_QUANTITY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_VALUE_FOR_QUANTITY = factory.getOWLObjectProperty(IRI.create("http://qudt.org/schema/qudt#valueQuantity"));

    /* ***************************************************
     * Object Property http://voag.linkedmodel.org/schema/voag#hasCatalogEntry
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CATALOG_ENTRY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_CATALOG_ENTRY = factory.getOWLObjectProperty(IRI.create("http://voag.linkedmodel.org/schema/voag#hasCatalogEntry"));

    /* ***************************************************
     * Object Property http://voag.linkedmodel.org/schema/voag#hasLicenseType
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLICENSETYPE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLICENSETYPE = factory.getOWLObjectProperty(IRI.create("http://voag.linkedmodel.org/schema/voag#hasLicenseType"));

    /* ***************************************************
     * Object Property http://voag.linkedmodel.org/schema/voag#withAttributionTo
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property WITH_ATTRIBUTION_TO.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WITH_ATTRIBUTION_TO = factory.getOWLObjectProperty(IRI.create("http://voag.linkedmodel.org/schema/voag#withAttributionTo"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/dtype#compositeOf
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPOSITE_OF.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPOSITE_OF = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#compositeOf"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/dtype#defaultValue
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEFAULT_VALUE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEFAULT_VALUE = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#defaultValue"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/dtype#derivedFrom
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DERIVED_FROM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DERIVED_FROM = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#derivedFrom"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/dtype#hasMember
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_MEMBER.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_MEMBER = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#hasMember"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/dtype#refersTo
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property REFERS_TO.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REFERS_TO = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#refersTo"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/dtype#value
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property VALUE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LM_VALUE = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#value"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#hasCatalogEntry
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CATALOG_ENTRY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LM_HAS_CATALOG_ENTRY = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#hasCatalogEntry"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#hasGraphRole
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_GRAPH_ROLE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_GRAPH_ROLE = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#hasGraphRole"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#hasLicenseType
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLICENSETYPE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LM_HASLICENSETYPE = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#hasLicenseType"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#ownedBy
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWNED_BY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWNED_BY = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#ownedBy"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#owner
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWNER.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWNER = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#owner"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#owningParty
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWNING_PARTY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWNING_PARTY = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#owningParty"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#reifiableBy
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property REIFIABLE_BY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REIFIABLE_BY = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#reifiableBy"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#usesNonImportedResource
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property USES_NON_IMPORTED_RESOURCE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_USES_NON_IMPORTED_RESOURCE = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#usesNonImportedResource"));

    /* ***************************************************
     * Object Property http://www.linkedmodel.org/schema/vaem#withAttributionTo
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property WITH_ATTRIBUTION_TO.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LM_WITH_ATTRIBUTION_TO = factory.getOWLObjectProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#withAttributionTo"));

    /* ***************************************************
     * Object Property http://www.w3.org/2003/01/geo/wgs84_pos#location
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property LOCATION.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_LOCATION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2003/01/geo/wgs84_pos#location"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/actsOnProperty
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property ACTS_ON_PROPERTY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ACTS_ON_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/actsOnProperty"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/hasFeatureOfInterest
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_FEATURE_OF_INTEREST.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_FEATURE_OF_INTEREST = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/hasFeatureOfInterest"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/hasResult
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_RESULT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_RESULT = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/hasResult"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/hasSample
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_SAMPLE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_SAMPLE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/hasSample"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/hosts
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HOSTS.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HOSTS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/hosts"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/isActedOnBy
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_ACTED_ON_BY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_ACTED_ON_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/isActedOnBy"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/isFeatureOfInterestOf
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_FEATURE_OF_INTEREST_OF.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_FEATURE_OF_INTEREST_OF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/isFeatureOfInterestOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/isHostedBy
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_HOSTED_BY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_HOSTED_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/isHostedBy"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/isObservedBy
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_OBSERVED_BY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_OBSERVED_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/isObservedBy"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/isResultOf
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_RESULT_OF.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_RESULT_OF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/isResultOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/isSampleOf
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_SAMPLE_OF.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_SAMPLE_OF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/isSampleOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/madeActuation
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADE_ACTUATION.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADE_ACTUATION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/madeActuation"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/madeByActuator
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADE_BY_ACTUATOR.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADE_BY_ACTUATOR = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/madeByActuator"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/madeBySampler
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADE_BY_SAMPLER.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADE_BY_SAMPLER = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/madeBySampler"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/madeBySensor
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADE_BY_SENSOR.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADE_BY_SENSOR = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/madeBySensor"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/madeObservation
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADE_OBSERVATION.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADE_OBSERVATION = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/madeObservation"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/madeSampling
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADE_SAMPLING.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADE_SAMPLING = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/madeSampling"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/observedProperty
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property OBSERVED_PROPERTY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OBSERVED_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/observedProperty"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/observes
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property OBSERVES.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OBSERVES = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/observes"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/phenomenonTime
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property PHENOMENON_TIME.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PHENOMENON_TIME = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/phenomenonTime"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/sosa/usedProcedure
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property USED_PROCEDURE.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_USED_PROCEDURE = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/sosa/usedProcedure"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/deployedOnPlatform
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEPLOYED_ON_PLATFORM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEPLOYED_ON_PLATFORM = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/deployedOnPlatform"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/deployedSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEPLOYED_SYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEPLOYED_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/deployedSystem"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/detects
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property DETECTS.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DETECTS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/detects"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/forProperty
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property FOR_PROPERTY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FOR_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/forProperty"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/hasDeployment
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DEPLOYMENT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DEPLOYMENT = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/hasDeployment"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/hasInput
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_INPUT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_INPUT = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/hasInput"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/hasOutput
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_OUTPUT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_OUTPUT = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/hasOutput"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/hasProperty
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PROPERTY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/hasProperty"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/hasSubSystem
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_SUBSYSTEM.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_SUBSYSTEM = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/hasSubSystem"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/implementedBy
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IMPLEMENTED_BY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IMPLEMENTED_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/implementedBy"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/implements
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IMPLEMENTS.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IMPLEMENTS = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/implements"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/inDeployment
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IN_DEPLOYMENT.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IN_DEPLOYMENT = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/inDeployment"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/isPropertyOf
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PROPERTY_OF.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PROPERTY_OF = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/isPropertyOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/isProxyFor
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PROXY_FOR.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PROXY_FOR = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/isProxyFor"));

    /* ***************************************************
     * Object Property http://www.w3.org/ns/ssn/wasOriginatedBy
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the object property WAS_ORIGINATED_BY.<p>
     *
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WAS_ORIGINATED_BY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/ns/ssn/wasOriginatedBy"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#abbreviation
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property ABBREVIATION.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_ABBREVIATION = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#abbreviation"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#code
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property CODE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_CODE = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#code"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#conversionCoefficient
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONVERSION_COEFFICIENT.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_CONVERSION_COEFFICIENT = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#conversionCoefficient"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#conversionMultiplier
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONVERSION_MULTIPLIER.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_CONVERSION_MULTIPLIER = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#conversionMultiplier"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#conversionOffset
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property CONVERSION_OFFSET.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_CONVERSION_OFFSET = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#conversionOffset"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#currencyExponent
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property CURRENCY_EXPONENT.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_CURRENCY_EXPONENT = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#currencyExponent"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#description
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIPTION.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#description"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#exactConstant
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property EXACT_CONSTANT.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_EXACT_CONSTANT = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#exactConstant"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#literal
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property LITERAL.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_LITERAL = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#literal"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#negativeDeltaLimit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property NEGATIVE_DELTA_LIMIT.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_NEGATIVE_DELTA_LIMIT = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#negativeDeltaLimit"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#numericValue
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property NUMERIC_VALUE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_NUMERIC_VALUE = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#numericValue"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#order
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property ORDER.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_ORDER = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#order"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#positiveDeltaLimit
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property POSITIVE_DELTA_LIMIT.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_POSITIVE_DELTA_LIMIT = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#positiveDeltaLimit"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#relativeStandardUncertainty
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property RELATIVE_STANDARD_UNCERTAINTY.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_RELATIVE_STANDARD_UNCERTAINTY = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#relativeStandardUncertainty"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#standardUncertainty
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property STANDARD_UNCERTAINTY.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_STANDARD_UNCERTAINTY = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#standardUncertainty"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#symbol
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property SYMBOL.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_SYMBOL = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#symbol"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#typePrefix
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property TYPE_PREFIX.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_TYPE_PREFIX = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#typePrefix"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#uneceCommonCode
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property UNECE_COMMON_CODE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_UNECE_COMMON_CODE = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#uneceCommonCode"));

    /* ***************************************************
     * Data Property http://qudt.org/schema/qudt#vectorMagnitude
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property VECTOR_MAGNITUDE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_VECTOR_MAGNITUDE = factory.getOWLDataProperty(IRI.create("http://qudt.org/schema/qudt#vectorMagnitude"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/dtype#code
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property CODE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_LM_CODE = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#code"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/dtype#literal
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property LITERAL.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_LM_LITERAL = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#literal"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/dtype#order
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property ORDER.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_LM_ORDER = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#order"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/dtype#position
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property CODE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_LM_POSITION = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/dtype#position"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#date
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_DATE = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#date"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#dateCreated
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property DATE_CREATED.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_DATE_CREATED = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#dateCreated"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#description
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIPTION.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_LM_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#description"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#lastUpdated
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property LAST_UPDATED.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_LAST_UPDATED = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#lastUpdated"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#name
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#name"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#namespace
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAMESPACE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_NAMESPACE = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#namespace"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#namespacePrefix
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAMESPACE_PREFIX.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_NAMESPACE_PREFIX = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#namespacePrefix"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#owner
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWNER.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_OWNER = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#owner"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#releaseDate
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property RELEASE_DATE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_RELEASE_DATE = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#releaseDate"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#revision
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property REVISION.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_REVISION = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#revision"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#title
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property TITLE.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_TITLE = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#title"));

    /* ***************************************************
     * Data Property http://www.linkedmodel.org/schema/vaem#url
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property URL.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_URL = factory.getOWLDataProperty(IRI.create("http://www.linkedmodel.org/schema/vaem#url"));

    /* ***************************************************
     * Data Property http://www.w3.org/ns/sosa/hasSimpleResult
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_SIMPLE_RESULT.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_SIMPLE_RESULT = factory.getOWLDataProperty(IRI.create("http://www.w3.org/ns/sosa/hasSimpleResult"));

    /* ***************************************************
     * Data Property http://www.w3.org/ns/sosa/resultTime
     */

    /**
     * A constant to give access to the Manchester OWL API representation of the data property RESULT_TIME.<p>
     *
     */
    public static final OWLDataProperty DATA_PROPERTY_RESULT_TIME = factory.getOWLDataProperty(IRI.create("http://www.w3.org/ns/sosa/resultTime"));


}
